In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\Shivni\Desktop\Marketing_analysis\data\raw\tech_advertising_campaigns_dataset.csv")

In [4]:
df.head()

,campaign_id,campaign_objective,platform,ad_placement,device_type,operating_system,creative_format,creative_size,ad_copy_length,has_call_to_action,...,avg_session_duration_seconds,pages_per_session,industry_vertical,budget_tier,CTR,CPC,conversion_rate,CPA,ROAS,profit
0,CAMP_00001,Lead Generation,Facebook,Search,Mobile,Android,Text,728x90,Short,False,...,70,2.00,E-commerce,High,0.606,2.23,0.498,448.23,0.32,-606.79
1,CAMP_00002,Engagement,Facebook,Feed,Mobile,iOS,Image,320x50,Long,True,...,105,2.74,Finance,Medium,0.932,2.48,1.071,231.63,1.49,570.04
2,CAMP_00003,Conversions,Google Ads,Feed,Tablet,iOS,Video,1920x1080,Short,False,...,149,3.97,Healthcare,Low,1.033,3.88,5.357,72.43,6.68,2468.70
3,CAMP_00004,Conversions,LinkedIn,Search,Desktop,iOS,Carousel,1920x1080,Short,False,...,147,2.49,Education,Medium,1.573,8.29,2.439,339.89,0.49,-517.39
4,CAMP_00005,Brand Awareness,Facebook,Stories,Mobile,iOS,Image,1920x1080,Short,False,...,81,3.04,SaaS,Low,1.409,1.41,0.000,0.00,0.00,-425.82

In [4]:
df.size

410000

In [6]:
df.shape

(10000, 41)

In [7]:
df.columns.tolist()

['campaign_id',
 'campaign_objective',
 'platform',
 'ad_placement',
 'device_type',
 'operating_system',
 'creative_format',
 'creative_size',
 'ad_copy_length',
 'has_call_to_action',
 'creative_emotion',
 'creative_age_days',
 'target_audience_age',
 'target_audience_gender',
 'audience_interest_category',
 'income_bracket',
 'purchase_intent_score',
 'retargeting_flag',
 'start_date',
 'quarter',
 'day_of_week',
 'hour_of_day',
 'campaign_day',
 'quality_score',
 'actual_cpc',
 'impressions',
 'clicks',
 'conversions',
 'ad_spend',
 'revenue',
 'bounce_rate',
 'avg_session_duration_seconds',
 'pages_per_session',
 'industry_vertical',
 'budget_tier',
 'CTR',
 'CPC',
 'conversion_rate',
 'CPA',
 'ROAS',
 'profit']

In [8]:
for columns in df.columns:
    print(columns)

campaign_id
campaign_objective
platform
ad_placement
device_type
operating_system
creative_format
creative_size
ad_copy_length
has_call_to_action
creative_emotion
creative_age_days
target_audience_age
target_audience_gender
audience_interest_category
income_bracket
purchase_intent_score
retargeting_flag
start_date
quarter
day_of_week
hour_of_day
campaign_day
quality_score
actual_cpc
impressions
clicks
conversions
ad_spend
revenue
bounce_rate
avg_session_duration_seconds
pages_per_session
industry_vertical
budget_tier
CTR
CPC
conversion_rate
CPA
ROAS
profit

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 41 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   campaign_id                   10000 non-null  object
 1   campaign_objective            10000 non-null  object
 2   platform                      10000 non-null  object
 3   ad_placement                  10000 non-null  object
 4   device_type                   10000 non-null  object
 5   operating_system              10000 non-null  object
 6   creative_format               10000 non-null  object
 7   creative_size                 10000 non-null  object
 8   ad_copy_length                10000 non-null  object
 9   has_call_to_action            10000 non-null  bool
 10  creative_emotion              10000 non-null  object
 11  creative_age_days             10000 non-null  int64
 12  target_audience_age           10000 non-null  object
 13  target_audience_gender        10000 non-null  object
 14  audience_interest_category    10000 non-null  object
 15  income_bracket                10000 non-null  object
 16  purchase_intent_score         10000 non-null  object
 17  retargeting_flag              10000 non-null  bool
 18  start_date                    10000 non-null  object
 19  quarter                       10000 non-null  int64
 20  day_of_week                   10000 non-null  object
 21  hour_of_day                   10000 non-null  int64
 22  campaign_day                  10000 non-null  int64
 23  quality_score                 10000 non-null  int64
 24  actual_cpc                    10000 non-null  float64
 25  impressions                   10000 non-null  int64
 26  clicks                        10000 non-null  int64
 27  conversions                   10000 non-null  int64
 28  ad_spend                      10000 non-null  float64
 29  revenue                       10000 non-null  float64
 30  bounce_rate                   10000 non-null  float64
 31  avg_session_duration_seconds  10000 non-null  int64
 32  pages_per_session             10000 non-null  float64
 33  industry_vertical             10000 non-null  object
 34  budget_tier                   10000 non-null  object
 35  CTR                           10000 non-null  float64
 36  CPC                           10000 non-null  float64
 37  conversion_rate               10000 non-null  float64
 38  CPA                           10000 non-null  float64
 39  ROAS                          10000 non-null  float64
 40  profit                        10000 non-null  float64
dtypes: bool(2), float64(11), int64(9), object(19)
memory usage: 3.0+ MB

In [10]:
df.isnull().sum()

campaign_id                     0
campaign_objective              0
platform                        0
ad_placement                    0
device_type                     0
operating_system                0
creative_format                 0
creative_size                   0
ad_copy_length                  0
has_call_to_action              0
creative_emotion                0
creative_age_days               0
target_audience_age             0
target_audience_gender          0
audience_interest_category      0
income_bracket                  0
purchase_intent_score           0
retargeting_flag                0
start_date                      0
quarter                         0
day_of_week                     0
hour_of_day                     0
campaign_day                    0
quality_score                   0
actual_cpc                      0
impressions                     0
clicks                          0
conversions                     0
ad_spend                        0
revenue                         0
bounce_rate                     0
avg_session_duration_seconds    0
pages_per_session               0
industry_vertical               0
budget_tier                     0
CTR                             0
CPC                             0
conversion_rate                 0
CPA                             0
ROAS                            0
profit                          0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df["campaign_id"].duplicated().sum()

np.int64(0)

In [13]:
pd.options.display.max_columns = 45

In [14]:
df.head()

,campaign_id,campaign_objective,platform,ad_placement,device_type,operating_system,creative_format,creative_size,ad_copy_length,has_call_to_action,creative_emotion,creative_age_days,target_audience_age,target_audience_gender,audience_interest_category,income_bracket,purchase_intent_score,retargeting_flag,start_date,quarter,day_of_week,hour_of_day,campaign_day,quality_score,actual_cpc,impressions,clicks,conversions,ad_spend,revenue,bounce_rate,avg_session_duration_seconds,pages_per_session,industry_vertical,budget_tier,CTR,CPC,conversion_rate,CPA,ROAS,profit
0,CAMP_00001,Lead Generation,Facebook,Search,Mobile,Android,Text,728x90,Short,False,Curiosity,72,45-54,Female,Shoppers,<$50K,Medium,False,2024-03-06,1,Wednesday,18,34,5,2.23,66329,402,2,896.46,289.67,67.75,70,2.00,E-commerce,High,0.606,2.23,0.498,448.23,0.32,-606.79
1,CAMP_00002,Engagement,Facebook,Feed,Mobile,iOS,Image,320x50,Long,True,Neutral,62,65+,Female,Business Professionals,$50K-$100K,Medium,False,2024-01-26,1,Friday,6,22,5,2.48,50094,467,5,1158.16,1728.20,63.73,105,2.74,Finance,Medium,0.932,2.48,1.071,231.63,1.49,570.04
2,CAMP_00003,Conversions,Google Ads,Feed,Tablet,iOS,Video,1920x1080,Short,False,Urgency,79,65+,Male,Tech Enthusiasts,<$50K,High,False,2025-05-15,2,Thursday,1,32,4,3.88,10842,112,6,434.56,2903.26,31.93,149,3.97,Healthcare,Low,1.033,3.88,5.357,72.43,6.68,2468.70
3,CAMP_00004,Conversions,LinkedIn,Search,Desktop,iOS,Carousel,1920x1080,Short,False,Joy,57,35-44,All,Shoppers,<$50K,Low,False,2024-07-21,3,Sunday,7,32,4,8.29,7820,123,3,1019.67,502.28,65.52,147,2.49,Education,Medium,1.573,8.29,2.439,339.89,0.49,-517.39
4,CAMP_00005,Brand Awareness,Facebook,Stories,Mobile,iOS,Image,1920x1080,Short,False,Joy,17,25-34,Female,Students,$100K-$200K,Low,False,2025-03-09,1,Sunday,17,52,7,1.41,21436,302,0,425.82,0.00,68.95,81,3.04,SaaS,Low,1.409,1.41,0.000,0.00,0.00,-425.82

In [27]:
print("Click > Impressions:",(df["clicks"]>df["impressions"]).sum())
print("Conversion > Click:",(df["conversions"]>df["clicks"]).sum())
print("Negative Ad Revenue:",(df["ad_spend"]<0).sum())
print("Negative Revenue:",(df["revenue"]<0).sum())
print("Negative Impressions:",(df["impressions"]<0).sum())
print("Negative Clicks:",(df["clicks"]<0).sum())
print("Negative Conversions:",(df["conversions"]<0).sum())

Click > Impressions: 0
Conversion > Click: 0
Negative Ad Revenue: 0
Negative Revenue: 0
Negative Impressions: 0
Negative Clicks: 0
Negative Conversions: 0

In [34]:
df["CTR_calc"] = (df["clicks"]/df["impressions"])*100
df["CPC_calc"] = df["ad_spend"]/df["clicks"]
df["conversion_rate_calc"] = (df["conversions"]/df["clicks"])*100
df["CPA_calc"] = df["ad_spend"]/df["conversions"]
df["ROAS_calc"] = df["revenue"]/df["ad_spend"]
df["profit_calc"] = df["revenue"] - df["ad_spend"]

In [41]:
print("CTR max difference:", (df["CTR_calc"]-df["CTR"]).abs().max())
print("CPC max difference:",(df["CPC_calc"]-df["CPC"]).abs().max())
print("Conversion Rate max differnce:",(df["conversion_rate_calc"]-df["conversion_rate"]).abs().max())
print("CPA max difference:",(df["CPA_calc"]-df["CPA"]).abs().max())
print("ROAS max difference:",(df["ROAS_calc"]-df["ROAS"]).abs().max())
print("Profit max difference:",(df["profit_calc"]-df["profit"]).abs().max())

CTR max difference: 0.0004999709825315168
CPC max difference: 3.552713678800501e-15
Conversion Rate max differnce: 0.0005000000000006111
CPA max difference: inf
ROAS max difference: 0.004999999999999893
Profit max difference: 4.656612873077393e-10

In [43]:
df.describe().T

C:\Users\Shivni\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,count,mean,std,min,25%,50%,75%,max
creative_age_days,10000.0,4.537430e+01,26.171100,1.000000,22.000000,45.000000,68.000000,9.000000e+01
quarter,10000.0,2.419100e+00,1.132424,1.000000,1.000000,2.000000,3.000000,4.000000e+00
hour_of_day,10000.0,1.148250e+01,6.932308,0.000000,5.000000,12.000000,18.000000,2.300000e+01
campaign_day,10000.0,4.542970e+01,26.071107,1.000000,23.000000,45.000000,68.000000,9.000000e+01
quality_score,10000.0,5.527400e+00,1.553541,1.000000,4.000000,6.000000,7.000000,1.000000e+01
actual_cpc,10000.0,3.290336e+00,2.453852,0.300000,1.510000,2.430000,4.530000,1.603000e+01
impressions,10000.0,7.053922e+04,91339.733246,5000.000000,16958.500000,37469.500000,83213.750000,5.000000e+05
clicks,10000.0,1.526436e+03,2412.164582,10.000000,290.000000,718.000000,1746.000000,4.000000e+04
conversions,10000.0,6.556880e+01,183.404876,0.000000,5.000000,16.000000,55.000000,5.384000e+03
ad_spend,10000.0,4.345566e+03,6917.481037,8.690000,666.307500,1895.670000,4996.160000,4.999968e+04
revenue,10000.0,2.841577e+04,89284.609131,0.000000,1608.910000,6099.240000,22165.825000,2.800397e+06
bounce_rate,10000.0,5.252850e+01,17.706165,10.000000,40.087500,53.580000,65.472500,9.000000e+01
avg_session_duration_seconds,10000.0,1.009566e+02,46.541295,10.000000,68.000000,100.000000,132.000000,2.770000e+02
pages_per_session,10000.0,3.113223e+00,1.369884,1.000000,2.160000,2.830000,3.740000,8.510000e+00
CTR,10000.0,2.314340e+00,1.573316,0.100000,1.172000,1.920000,3.017250,8.000000e+00
CPC,10000.0,3.290336e+00,2.453852,0.300000,1.510000,2.430000,4.530000,1.603000e+01
conversion_rate,10000.0,3.644033e+00,4.354338,0.000000,1.005000,2.165500,4.493250,2.500000e+01
CPA,10000.0,1.908959e+02,295.614462,0.000000,40.640000,99.460000,225.457500,6.379940e+03
ROAS,10000.0,7.524918e+00,14.985237,0.000000,1.197500,3.150000,7.950000,4.873000e+02
profit,10000.0,2.407020e+04,86416.098554,-36939.840000,209.480000,3302.535000,16641.877500,2.750398e+06
ctc_calc,10000.0,2.314337e+00,1.573320,0.100334,1.171654,1.920044,3.017382,8.000000e+00
CTR_calc,10000.0,2.314337e+00,1.573320,0.100334,1.171654,1.920044,3.017382,8.000000e+00
CPC_calc,10000.0,3.290336e+00,2.453852,0.300000,1.510000,2.430000,4.530000,1.603000e+01
conversion_rate_calc,10000.0,3.644035e+00,4.354337,0.000000,1.005025,2.165576,4.493235,2.500000e+01
CPA_calc,10000.0,inf,NaN,1.723636,51.853877,120.154467,281.588290,inf
ROAS_calc,10000.0,7.524944e+00,14.985169,0.000000,1.196797,3.146445,7.952585,4.873003e+02
profit_calc,10000.0,2.407020e+04,86416.098554,-36939.840000,209.480000,3302.535000,16641.877500,2.750398e+06

In [45]:
df["ctc_calc"].drop

<bound method Series.drop of 0       0.606070
1       0.932247
2       1.033020
3       1.572890
4       1.408845
          ...
9995    0.765089
9996    2.384457
9997    2.392879
9998    1.139499
9999    0.832650
Name: ctc_calc, Length: 10000, dtype: float64>

In [5]:
categorical_cols = df.select_dtypes(include = ["object","bool"]).columns

for col in categorical_cols:
    print(f"\n---{col}---")
    print(df[col].value_counts())

---campaign_id---
campaign_id
CAMP_00001    1
CAMP_00002    1
CAMP_00003    1
CAMP_00004    1
CAMP_00005    1
             ..
CAMP_09996    1
CAMP_09997    1
CAMP_09998    1
CAMP_09999    1
CAMP_10000    1
Name: count, Length: 10000, dtype: int64

---campaign_objective---
campaign_objective
Lead Generation    3563
Conversions        2946
Brand Awareness    2043
App Installs        746
Engagement          702
Name: count, dtype: int64

---platform---
platform
Google Ads    2933
Facebook      2527
LinkedIn      1468
TikTok        1213
Twitter       1029
Instagram      830
Name: count, dtype: int64

---ad_placement---
ad_placement
Feed               3491
Search             2067
Stories            1995
Display Network    1189
In-Stream Video     764
Sidebar             494
Name: count, dtype: int64

---device_type---
device_type
Mobile     5430
Desktop    3556
Tablet     1014
Name: count, dtype: int64

---operating_system---
operating_system
Android    2984
iOS        2550
Windows    2486
macOS      1501
Other       479
Name: count, dtype: int64

---creative_format---
creative_format
Image          3522
Video          2934
Carousel       1531
Text            809
Interactive     712
Story           492
Name: count, dtype: int64

---creative_size---
creative_size
1920x1080    2497
1080x1080    2468
300x250      2009
728x90       1540
320x50       1018
1200x628      468
Name: count, dtype: int64

---ad_copy_length---
ad_copy_length
Medium    4052
Short     3984
Long      1964
Name: count, dtype: int64

---has_call_to_action---
has_call_to_action
True     6939
False    3061
Name: count, dtype: int64

---creative_emotion---
creative_emotion
Joy          2549
Trust        2016
Urgency      2001
Curiosity    1478
Fear         1012
Neutral       944
Name: count, dtype: int64

---target_audience_age---
target_audience_age
25-34    2933
35-44    2463
18-24    1838
45-54    1563
55-64     806
65+       397
Name: count, dtype: int64

---target_audience_gender---
target_audience_gender
Male      3569
Female    3518
All       2913
Name: count, dtype: int64

---audience_interest_category---
audience_interest_category
Tech Enthusiasts          2489
Business Professionals    2480
Gamers                    1530
Students                  1432
Shoppers                  1256
Health & Fitness           813
Name: count, dtype: int64

---income_bracket---
income_bracket
$50K-$100K     3883
$100K-$200K    2588
<$50K          2463
>$200K         1066
Name: count, dtype: int64

---purchase_intent_score---
purchase_intent_score
Medium    4508
Low       3010
High      2482
Name: count, dtype: int64

---retargeting_flag---
retargeting_flag
False    7530
True     2470
Name: count, dtype: int64

---start_date---
start_date
2025-01-21    25
2025-07-15    24
2025-03-06    24
2024-01-18    24
2024-03-10    23
              ..
2024-01-06     5
2025-02-16     5
2025-10-04     4
2024-02-04     4
2024-05-18     4
Name: count, Length: 761, dtype: int64

---day_of_week---
day_of_week
Tuesday      1471
Thursday     1460
Monday       1441
Saturday     1435
Sunday       1418
Wednesday    1417
Friday       1358
Name: count, dtype: int64

---industry_vertical---
industry_vertical
E-commerce    2507
SaaS          2490
Healthcare    2090
Finance       1430
Education      984
Gaming         499
Name: count, dtype: int64

---budget_tier---
budget_tier
Medium    4467
Low       3472
High      2061
Name: count, dtype: int64

In [6]:
print("Zero impressions:",(df["impressions"]==0).sum())
print("Zero Clicks:",(df["clicks"]==0).sum())
print("Zero Conversions:",(df["conversions"]==0).sum())
print("Zero Ad_Spend:",(df["ad_spend"]==0).sum())

Zero impressions: 0
Zero Clicks: 0
Zero Conversions: 594
Zero Ad_Spend: 0

In [7]:
df.to_csv(r"C:\Users\Shivni\Desktop\Marketing_analysis\data\cleaned\marketing_campaigns_data_audit.csv")